name: setup-java
description: https://github.com/actions/setup-java
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
